// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockPortfolioApp;

#nullable disable

namespace Investify.Migrations
{
    [DbContext(typeof(StockDbContext))]
    [Migration("20250526040102_raping-the-data-base")]
    partial class rapingthedatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Investify.Models.BrokerageCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BrokerageCompanies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Thndr | ثندر"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Arabiya Online | عربية أونلاين"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ostoul | أسطول"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tycoon | تايكون"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Beltone | بلتون"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Mirage | ميراج"
                        });
                });

            modelBuilder.Entity("Investify.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AllTimePeak")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExtraSector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Indicator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("LastPrice")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("MonthlyPeak")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Sector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SixMonthsPeak")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal?>("YearPeak")
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "AALR",
                            ExtraSector = "",
                            LastPrice = 20.000m,
                            Name = "العامة لاستصلاح الأراضي",
                            Sector = "عقارات"
                        },
                        new
                        {
                            Id = 2,
                            Code = "ABUK",
                            ExtraSector = "أسمدة",
                            Indicator = "EGX30",
                            LastPrice = 62.000m,
                            Name = "أبوقير للأسمدة",
                            Sector = "موارد أساسية"
                        },
                        new
                        {
                            Id = 3,
                            Code = "ACAMD",
                            LastPrice = 0.000m,
                            Name = "العربية أصول",
                            Sector = "عقارات"
                        },
                        new
                        {
                            Id = 4,
                            Code = "ACAP",
                            Indicator = "EGX70",
                            LastPrice = 2.950m,
                            Name = "ايه كابيتال القابضة",
                            Sector = "عقارات"
                        },
                        new
                        {
                            Id = 5,
                            Code = "ACGC",
                            Indicator = "EGX70",
                            LastPrice = 6.870m,
                            Name = "العربية لحليج الأقطان",
                            Sector = "النسيج"
                        },
                        new
                        {
                            Id = 6,
                            AllTimePeak = 0.000m,
                            Code = "ACRO",
                            Indicator = "",
                            LastPrice = 0.000m,
                            MonthlyPeak = 0.000m,
                            Name = "اكرو مصر",
                            Sector = "مقاولات و إنشاءات هندسية",
                            SixMonthsPeak = 0.000m,
                            YearPeak = 0.000m
                        },
                        new
                        {
                            Id = 7,
                            Code = "ACTF",
                            LastPrice = 0.000m,
                            Name = "أكت فاينانشال",
                            Sector = "خدمات مالية غير مصرفية"
                        },
                        new
                        {
                            Id = 8,
                            Code = "ADIB",
                            Indicator = "EGX30",
                            LastPrice = 36.980m,
                            Name = "مصرف أبو ظبي الإسلامي",
                            Sector = "البنوك"
                        },
                        new
                        {
                            Id = 9,
                            Code = "ADPC",
                            Indicator = "EGX70",
                            LastPrice = 2.400m,
                            Name = "آراب ديري باندا",
                            Sector = "الأغذية"
                        },
                        new
                        {
                            Id = 10,
                            Code = "ADRI",
                            LastPrice = 0.000m,
                            Name = "اراب للتنمية",
                            Sector = "الشركات الصغيرة و المتوسطة"
                        },
                        new
                        {
                            Id = 11,
                            Code = "AFDI",
                            Indicator = "",
                            LastPrice = 34.000m,
                            MonthlyPeak = 34.000m,
                            Name = "الأهلي للتنمية",
                            Sector = "خدمات مالية غير مصرفية"
                        },
                        new
                        {
                            Id = 12,
                            Code = "AFMC",
                            LastPrice = 0.000m,
                            Name = "مطاحن الإسكندرية",
                            Sector = "الأغذية"
                        },
                        new
                        {
                            Id = 13,
                            Code = "AIFI",
                            LastPrice = 0.790m,
                            Name = "أطلس",
                            Sector = "عقارات"
                        },
                        new
                        {
                            Id = 14,
                            Code = "AIH",
                            Indicator = "EGX70",
                            LastPrice = 0.490m,
                            Name = "ارابيا انفستمنتس هولدنج",
                            Sector = "خدمات مالية غير مصرفية"
                        },
                        new
                        {
                            Id = 15,
                            Code = "AIVC",
                            LastPrice = 0.000m,
                            Name = "العرفة القابضة",
                            Sector = "منسوجات"
                        },
                        new
                        {
                            Id = 16,
                            Code = "AJWA",
                            LastPrice = 0.000m,
                            Name = "أجواء",
                            Sector = "الأغذية"
                        },
                        new
                        {
                            Id = 17,
                            Code = "ALCN",
                            Indicator = "EGX30",
                            LastPrice = 22.800m,
                            Name = "الإسكندرية لتداول الحاويات",
                            Sector = "خدمات النقل والشحن"
                        },
                        new
                        {
                            Id = 18,
                            Code = "ALEX",
                            LastPrice = 0.000m,
                            Name = "الإسكندرية للأسمنت",
                            Sector = "الأسمنت"
                        },
                        new
                        {
                            Id = 19,
                            Code = "ALUM",
                            ExtraSector = "ألمونيوم",
                            LastPrice = 0.000m,
                            Name = "الألومنيوم العربية",
                            Sector = "موارد أساسية"
                        },
                        new
                        {
                            Id = 20,
                            AllTimePeak = 2.000m,
                            Code = "AMER",
                            Indicator = "EGX70",
                            LastPrice = 1.140m,
                            MonthlyPeak = 1.150m,
                            Name = "عامر جروب",
                            Sector = "عقارات",
                            SixMonthsPeak = 1.500m,
                            YearPeak = 1.600m
                        },
                        new
                        {
                            Id = 21,
                            Code = "AMES",
                            LastPrice = 0.000m,
                            Name = "المركز الطبي الجديد - الإسكندرية",
                            Sector = "الصحة"
                        },
                        new
                        {
                            Id = 22,
                            Code = "AMIA",
                            Indicator = "EGX70",
                            LastPrice = 2.410m,
                            Name = "الملتقى العربي",
                            Sector = "المالي"
                        },
                        new
                        {
                            Id = 23,
                            Code = "AMOC",
                            ExtraSector = "",
                            Indicator = "EGX30",
                            LastPrice = 8.040m,
                            Name = "أموك",
                            Sector = "البتروكيماويات"
                        },
                        new
                        {
                            Id = 24,
                            Code = "ARAB",
                            Indicator = "EGX70",
                            LastPrice = 0.340m,
                            Name = "المطورون العرب",
                            Sector = "عقارات"
                        },
                        new
                        {
                            Id = 25,
                            Code = "ARCC",
                            ExtraSector = "أسمنت",
                            Indicator = "EGX70",
                            LastPrice = 13.630m,
                            Name = "العربية للأسمنت",
                            Sector = "مواد البناء"
                        },
                        new
                        {
                            Id = 26,
                            Code = "ASCM",
                            ExtraSector = "-",
                            Indicator = "EGX70",
                            LastPrice = 37.820m,
                            Name = "أسيك للتعدين",
                            Sector = "موارد أساسية"
                        },
                        new
                        {
                            Id = 27,
                            Code = "ASPI",
                            LastPrice = 0.000m,
                            Name = "اسباير كابيتال",
                            Sector = "خدمات مالية غير مصرفية"
                        },
                        new
                        {
                            Id = 28,
                            Code = "ASPW",
                            LastPrice = 0.000m,
                            Name = "العربية وبولفارا",
                            Sector = "منسوجات وسلع معمرة"
                        },
                        new
                        {
                            Id = 29,
                            Code = "ATLC",
                            Indicator = "EGX70",
                            LastPrice = 3.900m,
                            Name = "ايه تي ليس التوفيق",
                            Sector = "خدمات مالية غير مصرفية"
                        },
                        new
                        {
                            Id = 30,
                            Code = "ATQA",
                            ExtraSector = "حديد",
                            Indicator = "EGX70",
                            LastPrice = 4.420m,
                            Name = "عتاقة",
                            Sector = "موارد أساسية"
                        },
                        new
                        {
                            Id = 31,
                            Code = "BINV",
                            Indicator = "EGX30",
                            LastPrice = 25.250m,
                            Name = "بي انفستمنتس",
                            Sector = "خدمات مالية غير مصرفية"
                        },
                        new
                        {
                            Id = 32,
                            Code = "BIOC",
                            LastPrice = 0.000m,
                            Name = "جلاكسو سميثكلاين",
                            Sector = "الصحة"
                        },
                        new
                        {
                            Id = 33,
                            Code = "BTFH",
                            Indicator = "EGX30",
                            LastPrice = 2.910m,
                            Name = "بلتون القابضة",
                            Sector = "خدمات مالية غير مصرفية"
                        },
                        new
                        {
                            Id = 34,
                            Code = "CCAP",
                            Indicator = "EGX70",
                            LastPrice = 2.050m,
                            Name = "القلعة",
                            Sector = "خدمات مالية غير مصرفية"
                        },
                        new
                        {
                            Id = 35,
                            Code = "CERA",
                            ExtraSector = "سيراميك و خزف",
                            Indicator = "EGX70",
                            LastPrice = 0.810m,
                            Name = "ريماس",
                            Sector = "مواد البناء"
                        },
                        new
                        {
                            Id = 36,
                            Code = "CICH",
                            Indicator = "EGX70",
                            LastPrice = 5.600m,
                            Name = "سي اي كابيتال القابضة",
                            Sector = "خدمات مالية غير مصرفية"
                        },
                        new
                        {
                            Id = 37,
                            Code = "CIEB",
                            Indicator = "EGX30",
                            LastPrice = 19.290m,
                            Name = "كريدي أجريكول",
                            Sector = "البنوك"
                        },
                        new
                        {
                            Id = 38,
                            Code = "CIRA",
                            LastPrice = 0.000m,
                            Name = "القاهرة للأستثمار",
                            Sector = "المالي"
                        },
                        new
                        {
                            Id = 39,
                            Code = "CLHO",
                            Indicator = "EGX30",
                            LastPrice = 8.800m,
                            Name = "مستشفى كليوباترا",
                            Sector = "الصحة"
                        },
                        new
                        {
                            Id = 40,
                            AllTimePeak = 90.000m,
                            Code = "COMI",
                            ExtraSector = "",
                            Indicator = "EGX30",
                            LastPrice = 79.950m,
                            MonthlyPeak = 87.500m,
                            Name = "التجاري الدولي",
                            Sector = "البنوك",
                            SixMonthsPeak = 85.000m
                        },
                        new
                        {
                            Id = 41,
                            Code = "COPR",
                            LastPrice = 0.000m,
                            Name = "كوبر",
                            Sector = "المالي"
                        },
                        new
                        {
                            Id = 42,
                            Code = "COSG",
                            Indicator = "EGX70",
                            LastPrice = 0.236m,
                            Name = "القاهرة للزيوت",
                            Sector = "الأغذية"
                        },
                        new
                        {
                            Id = 43,
                            Code = "CSAG",
                            Indicator = "EGX70",
                            LastPrice = 23.050m,
                            Name = "القناة للتوكيلات",
                            Sector = "خدمات النقل والشحن"
                        },
                        new
                        {
                            Id = 44,
                            Code = "DGTZ",
                            Indicator = "EGX70",
                            LastPrice = 2.050m,
                            Name = "ديجيتايز",
                            Sector = "الشركات الصغيرة و المتوسطة"
                        },
                        new
                        {
                            Id = 45,
                            Code = "DOMT",
                            LastPrice = 0.000m,
                            Name = "دومتي",
                            Sector = "الأغذية"
                        },
                        new
                        {
                            Id = 46,
                            Code = "DSCW",
                            Indicator = "EGX70",
                            LastPrice = 1.600m,
                            Name = "دايس",
                            Sector = "الملابس"
                        },
                        new
                        {
                            Id = 47,
                            Code = "EAST",
                            Indicator = "EGX30",
                            LastPrice = 28.200m,
                            Name = "الشرقية للدخان",
                            Sector = "الأغذية"
                        },
                        new
                        {
                            Id = 48,
                            Code = "ECAP",
                            ExtraSector = "سيراميك و خزف",
                            Indicator = "EGX70",
                            LastPrice = 22.560m,
                            Name = "الجوهرة بورسلين",
                            Sector = "مواد البناء"
                        },
                        new
                        {
                            Id = 49,
                            Code = "EEII",
                            LastPrice = 1.310m,
                            Name = "العربية للصناعات الهندسية",
                            Sector = "خدمات و منتجات صناعية و سيارات"
                        },
                        new
                        {
                            Id = 50,
                            Code = "EGAS",
                            Indicator = "EGX70",
                            LastPrice = 45.025m,
                            Name = "غاز مصر",
                            Sector = "الغاز"
                        },
                        new
                        {
                            Id = 51,
                            Code = "EHDR",
                            Indicator = "EGX70",
                            LastPrice = 0.340m,
                            Name = "المصريين للإسكان",
                            Sector = "عقارات"
                        },
                        new
                        {
                            Id = 52,
                            Code = "EIUD",
                            Indicator = "EGX70",
                            LastPrice = 0.200m,
                            Name = "المصريين للإستثمار",
                            Sector = "عقارات"
                        },
                        new
                        {
                            Id = 53,
                            Code = "ELEC",
                            Indicator = "EGX70",
                            LastPrice = 2.840m,
                            Name = "الكابلات",
                            Sector = "خدمات و منتجات صناعية و سيارات"
                        },
                        new
                        {
                            Id = 54,
                            Code = "ELKA",
                            LastPrice = 0.000m,
                            Name = "القاهرة للإسكان",
                            Sector = "عقارات"
                        },
                        new
                        {
                            Id = 55,
                            Code = "ELSH",
                            Indicator = "EGX70",
                            LastPrice = 6.350m,
                            Name = "الشمس للإسكان",
                            Sector = "عقارات"
                        },
                        new
                        {
                            Id = 56,
                            Code = "ETRS",
                            Indicator = "EGX70",
                            LastPrice = 4.020m,
                            Name = "ايجيترانس",
                            Sector = "خدمات النقل والشحن"
                        },
                        new
                        {
                            Id = 57,
                            Code = "EXPA",
                            Indicator = "EGX70",
                            LastPrice = 15.520m,
                            Name = "بنك تنمية الصادرات",
                            Sector = "البنوك"
                        },
                        new
                        {
                            Id = 58,
                            AllTimePeak = 24.000m,
                            Code = "FWRY",
                            ExtraSector = "",
                            Indicator = "EGX30",
                            LastPrice = 8.150m,
                            MonthlyPeak = 6.000m,
                            Name = "فوري",
                            Sector = "اتصالات و اعلام و تكنولوجيا المعلومات",
                            SixMonthsPeak = 7.000m,
                            YearPeak = 6.000m
                        },
                        new
                        {
                            Id = 59,
                            Code = "GBCO",
                            Indicator = "EGX30",
                            LastPrice = 14.150m,
                            Name = "جي بي كورب",
                            Sector = "خدمات و منتجات صناعية و سيارات"
                        },
                        new
                        {
                            Id = 60,
                            Code = "GIHD",
                            LastPrice = 0.000m,
                            Name = "الغربية الإسلامية",
                            Sector = "عقارات"
                        },
                        new
                        {
                            Id = 61,
                            Code = "HELI",
                            Indicator = "EGX30",
                            LastPrice = 9.510m,
                            Name = "مصر الجديدة",
                            Sector = "عقارات"
                        },
                        new
                        {
                            Id = 62,
                            Code = "ICFC",
                            LastPrice = 0.000m,
                            Name = "الدولية للأسمدة",
                            Sector = "البتروكيماويات"
                        },
                        new
                        {
                            Id = 63,
                            Code = "IEEC",
                            Indicator = "EGX70",
                            LastPrice = 0.230m,
                            Name = "المشروعات الصناعية",
                            Sector = "التشييد"
                        },
                        new
                        {
                            Id = 64,
                            Code = "INFI",
                            LastPrice = 0.000m,
                            Name = "فوديكو",
                            Sector = "الأغذية"
                        },
                        new
                        {
                            Id = 65,
                            Code = "ISMA",
                            ExtraSector = "دواجن",
                            Indicator = "EGX70",
                            LastPrice = 8.260m,
                            Name = "اسماعيلية للدواجن",
                            Sector = "الأغذية"
                        },
                        new
                        {
                            Id = 66,
                            Code = "ISMQ",
                            ExtraSector = "حديد",
                            Indicator = "EGX70",
                            LastPrice = 4.250m,
                            Name = "الحديد و الصلب للمناجم و المحاجر",
                            Sector = "موارد أساسية"
                        },
                        new
                        {
                            Id = 67,
                            Code = "ISPH",
                            Indicator = "EGX70",
                            LastPrice = 5.510m,
                            Name = "ابن سينا",
                            Sector = "الصحة"
                        },
                        new
                        {
                            Id = 68,
                            Code = "KZPC",
                            ExtraSector = "مبيدات",
                            Indicator = "EGX70",
                            LastPrice = 11.000m,
                            Name = "كفر الزيات للمبيدات",
                            Sector = "موارد أساسية"
                        },
                        new
                        {
                            Id = 69,
                            Code = "LCSW",
                            ExtraSector = "سيراميك و خزف",
                            Indicator = "EGX70",
                            LastPrice = 23.270m,
                            Name = "ليسيكو",
                            Sector = "مواد البناء"
                        },
                        new
                        {
                            Id = 70,
                            Code = "MASR",
                            Indicator = "EGX30",
                            LastPrice = 0.000m,
                            Name = "مدينة نصر",
                            Sector = "عقارات"
                        },
                        new
                        {
                            Id = 71,
                            Code = "MCQE",
                            Indicator = "EGX70",
                            LastPrice = 28.300m,
                            Name = "مصر للأسمنت قنا",
                            Sector = "الأسمنت"
                        },
                        new
                        {
                            Id = 72,
                            AllTimePeak = 0.000m,
                            Code = "MENA",
                            Indicator = "EGX70",
                            LastPrice = 2.070m,
                            MonthlyPeak = 0.000m,
                            Name = "مينا",
                            Sector = "سياحة و ترفيه",
                            SixMonthsPeak = 0.000m,
                            YearPeak = 0.000m
                        },
                        new
                        {
                            Id = 73,
                            Code = "MEPA",
                            Indicator = "EGX70",
                            LastPrice = 1.250m,
                            Name = "العبوات",
                            Sector = "الصحة"
                        },
                        new
                        {
                            Id = 74,
                            Code = "MFPC",
                            ExtraSector = "بتروكيماويات",
                            Indicator = "EGX30",
                            LastPrice = 42.000m,
                            Name = "موبكو",
                            Sector = "موارد أساسية"
                        },
                        new
                        {
                            Id = 75,
                            Code = "MICH",
                            Indicator = "EGX70",
                            LastPrice = 36.000m,
                            Name = "مصر للكيماويات",
                            Sector = "البتروكيماويات"
                        },
                        new
                        {
                            Id = 76,
                            Code = "MPRC",
                            Indicator = "EGX70",
                            LastPrice = 28.510m,
                            Name = "الإنتاج الإعلامي",
                            Sector = "اتصالات و اعلام و تكنولوجيا المعلومات"
                        },
                        new
                        {
                            Id = 77,
                            Code = "MTIE",
                            Indicator = "EGX70",
                            LastPrice = 6.530m,
                            Name = "ام ام جروب",
                            Sector = "المالي"
                        },
                        new
                        {
                            Id = 78,
                            Code = "NCCW",
                            Indicator = "EGX70",
                            LastPrice = 3.850m,
                            Name = "النصر للأعمال المدنية",
                            Sector = "التشييد"
                        },
                        new
                        {
                            Id = 79,
                            Code = "OLFI",
                            Indicator = "EGX70",
                            LastPrice = 15.230m,
                            Name = "عبورلاند",
                            Sector = "الأغذية"
                        },
                        new
                        {
                            Id = 80,
                            Code = "ORHD",
                            Indicator = "EGX70",
                            LastPrice = 13.100m,
                            Name = "اوراسكوم للتنمية",
                            Sector = "عقارات"
                        },
                        new
                        {
                            Id = 81,
                            Code = "ORWE",
                            Indicator = "EGX30",
                            LastPrice = 24.670m,
                            Name = "النساجون",
                            Sector = "النسيج"
                        },
                        new
                        {
                            Id = 82,
                            Code = "PHAR",
                            Indicator = "EGX70",
                            LastPrice = 49.280m,
                            Name = "ايبيكو",
                            Sector = "الصحة"
                        },
                        new
                        {
                            Id = 83,
                            Code = "PHDC",
                            Indicator = "EGX30",
                            LastPrice = 5.900m,
                            Name = "بالم هيلز",
                            Sector = "عقارات"
                        },
                        new
                        {
                            Id = 84,
                            Code = "POUL",
                            ExtraSector = "دواجن",
                            Indicator = "EGX70",
                            LastPrice = 11.180m,
                            Name = "القاهرة للدواجن",
                            Sector = "الأغذية"
                        },
                        new
                        {
                            Id = 85,
                            Code = "PRCL",
                            ExtraSector = "سيراميك و خزف",
                            Indicator = "EGX70",
                            LastPrice = 10.890m,
                            Name = "شيني",
                            Sector = "مواد البناء"
                        },
                        new
                        {
                            Id = 86,
                            Code = "PRDC",
                            Indicator = "EGX70",
                            LastPrice = 3.270m,
                            Name = "بايونيرز بروبرتيز",
                            Sector = "خدمات مالية غير مصرفية"
                        },
                        new
                        {
                            Id = 87,
                            AllTimePeak = 0.000m,
                            Code = "Provider",
                            ExtraSector = "0",
                            Indicator = "",
                            LastPrice = 0.000m,
                            MonthlyPeak = 0.000m,
                            Name = "السمسار",
                            Sector = "",
                            SixMonthsPeak = 0.000m,
                            YearPeak = 0.000m
                        },
                        new
                        {
                            Id = 88,
                            Code = "RAYA",
                            Indicator = "EGX70",
                            LastPrice = 2.960m,
                            Name = "راية القابضة",
                            Sector = "خدمات مالية غير مصرفية"
                        },
                        new
                        {
                            Id = 89,
                            Code = "RMDA",
                            Indicator = "EGX70",
                            LastPrice = 3.620m,
                            Name = "راميدا",
                            Sector = "الصحة"
                        },
                        new
                        {
                            Id = 90,
                            Code = "SDTI",
                            LastPrice = 0.000m,
                            Name = "شارم دريمز",
                            Sector = "سياحة و ترفيه"
                        },
                        new
                        {
                            Id = 91,
                            Code = "SPMD",
                            LastPrice = 0.000m,
                            Name = "سبيد ميديكال",
                            Sector = "الصحة"
                        },
                        new
                        {
                            Id = 92,
                            Code = "SUGR",
                            Indicator = "EGX70",
                            LastPrice = 64.110m,
                            Name = "الدلتا للسكر",
                            Sector = "الأغذية"
                        },
                        new
                        {
                            Id = 93,
                            Code = "SWDY",
                            Indicator = "EGX30",
                            LastPrice = 95.000m,
                            Name = "السويدي",
                            Sector = "خدمات و منتجات صناعية و سيارات"
                        },
                        new
                        {
                            Id = 94,
                            Code = "TAQA",
                            Indicator = "EGX70",
                            LastPrice = 12.480m,
                            Name = "طاقة",
                            Sector = "بتروكيماويات"
                        },
                        new
                        {
                            Id = 95,
                            Code = "TMGH",
                            Indicator = "EGX30",
                            LastPrice = 59.980m,
                            Name = "طلعت مصطفى",
                            Sector = "عقارات"
                        },
                        new
                        {
                            Id = 96,
                            Code = "UNIP",
                            LastPrice = 0.000m,
                            Name = "يونيباك",
                            Sector = "ورق و مواد تعبئة و تغليف"
                        },
                        new
                        {
                            Id = 97,
                            Code = "UNIT",
                            LastPrice = 0.000m,
                            Name = "المتحدة للإسكان",
                            Sector = "عقارات"
                        },
                        new
                        {
                            Id = 98,
                            Code = "ZMID",
                            Indicator = "EGX70",
                            LastPrice = 7.500m,
                            Name = "زهراء المعادي",
                            Sector = "عقارات"
                        },
                        new
                        {
                            Id = 99,
                            Code = "مصاريف",
                            LastPrice = 0.000m,
                            Name = "خصم نقل"
                        },
                        new
                        {
                            Id = 100,
                            Code = "RREI",
                            LastPrice = 1.560m,
                            Name = "اليكو",
                            Sector = "عقارات"
                        },
                        new
                        {
                            Id = 101,
                            Code = "RUBX",
                            ExtraSector = "سيراميك و خزف",
                            LastPrice = 7.250m,
                            Name = "روبكس",
                            Sector = "مواد البناء"
                        },
                        new
                        {
                            Id = 102,
                            Code = "ADCI",
                            LastPrice = 0.000m,
                            Name = "أدكو",
                            Sector = "الصحة"
                        },
                        new
                        {
                            Id = 103,
                            Code = "ARVA",
                            ExtraSector = "محابس",
                            LastPrice = 0.000m,
                            Name = "العربية للمحابس",
                            Sector = "مواد البناء"
                        },
                        new
                        {
                            Id = 104,
                            Code = "AREH",
                            LastPrice = 0.000m,
                            Name = "المجموعة المصرية العقارية",
                            Sector = "عقارات"
                        },
                        new
                        {
                            Id = 106,
                            Code = "ANFI",
                            LastPrice = 0.000m,
                            Name = "الإسكندرية الوطنية للإستثمارات المالية",
                            Sector = "خدمات مالية غير مصرفية"
                        },
                        new
                        {
                            Id = 108,
                            Code = "BIDI",
                            LastPrice = 0.000m,
                            Name = "البدر للإستثمار والتنمية",
                            Sector = "الشركات الصغيرة والمتوسطة"
                        },
                        new
                        {
                            Id = 109,
                            Code = "BIGP",
                            LastPrice = 0.000m,
                            Name = "بي اي جي للتجارة والاستثمار"
                        },
                        new
                        {
                            Id = 110,
                            Code = "CAED",
                            LastPrice = 0.000m,
                            Name = "القاهرة للخدمات التعليمية",
                            Sector = "خدمات تعليمية"
                        },
                        new
                        {
                            Id = 111,
                            Code = "CANA",
                            LastPrice = 0.000m,
                            Name = "بنك قناة السويس",
                            Sector = "البنوك"
                        },
                        new
                        {
                            Id = 112,
                            Code = "CNFN",
                            LastPrice = 0.000m,
                            Name = "كونكت المالية القابضة",
                            Sector = "خدمات مالية غير مصرفية"
                        },
                        new
                        {
                            Id = 113,
                            Code = "CPCI",
                            LastPrice = 0.000m,
                            Name = "القاهرة للأدوية",
                            Sector = "الصحة"
                        },
                        new
                        {
                            Id = 114,
                            Code = "EASB",
                            LastPrice = 0.000m,
                            Name = "ثمار",
                            Sector = "خدمات مالية غير مصرفية"
                        },
                        new
                        {
                            Id = 115,
                            Code = "EDBM",
                            LastPrice = 0.000m,
                            Name = "ليفت سلاب",
                            Sector = "مقاولات و إنشاءات هندسية"
                        },
                        new
                        {
                            Id = 116,
                            Code = "EFIC",
                            ExtraSector = "-",
                            Indicator = "EGX70",
                            LastPrice = 140.010m,
                            Name = "المالية والصناعية",
                            Sector = "موارد أساسية"
                        },
                        new
                        {
                            Id = 117,
                            Code = "EFID",
                            Indicator = "EGX30",
                            LastPrice = 30.000m,
                            Name = "ايديتا",
                            Sector = "الأغذية"
                        },
                        new
                        {
                            Id = 118,
                            Code = "EFIH",
                            Indicator = "EGX30",
                            LastPrice = 20.320m,
                            Name = "اي فاينانس للاستثمارات المالية والرقمية",
                            Sector = "اتصالات و اعلام و تكنولوجيا المعلومات"
                        },
                        new
                        {
                            Id = 119,
                            Code = "EGAL",
                            ExtraSector = "ألمونيوم",
                            Indicator = "EGX70",
                            LastPrice = 113.210m,
                            Name = "مصر للألمونيوم",
                            Sector = "موارد أساسية"
                        },
                        new
                        {
                            Id = 120,
                            Code = "CITI",
                            LastPrice = 0.000m,
                            Name = "سيتي للتحاليل الطبية"
                        },
                        new
                        {
                            Id = 121,
                            Code = "EGTS",
                            Indicator = "EGX70",
                            LastPrice = 5.750m,
                            Name = "المصرية للمنتجعات السياحية",
                            Sector = "سياحة و ترفيه"
                        },
                        new
                        {
                            Id = 122,
                            Code = "EKHOA",
                            Indicator = "EGX30",
                            LastPrice = 32.420m,
                            Name = "القابضة المصرية الكويتية جنيه",
                            Sector = "خدمات مالية غير مصرفية"
                        },
                        new
                        {
                            Id = 123,
                            Code = "EKHO",
                            Indicator = "EGX30",
                            LastPrice = 0.820m,
                            Name = "القابضة المصرية الكويتية دولار",
                            Sector = "خدمات مالية غير مصرفية"
                        },
                        new
                        {
                            Id = 124,
                            Code = "ELNA",
                            LastPrice = 0.000m,
                            Name = "النصر لتصنيع الحاصلات الزراعية",
                            Sector = "الأغذية"
                        },
                        new
                        {
                            Id = 125,
                            Code = "ELWA",
                            LastPrice = 0.000m,
                            Name = "الوادي العالمية",
                            Sector = "سياحة و ترفيه"
                        },
                        new
                        {
                            Id = 126,
                            Code = "EMFD",
                            Indicator = "EGX30",
                            LastPrice = 7.590m,
                            Name = "اعمار مصر",
                            Sector = "عقارات"
                        },
                        new
                        {
                            Id = 127,
                            Code = "ENGC",
                            Indicator = "EGX70",
                            LastPrice = 0.000m,
                            Name = "ايكون",
                            Sector = "مقاولات و إنشاءات هندسية"
                        },
                        new
                        {
                            Id = 128,
                            Code = "EPCO",
                            ExtraSector = "دواجن",
                            Indicator = "EGX70",
                            LastPrice = 3.970m,
                            Name = "المصرية للدواجن",
                            Sector = "الأغذية"
                        },
                        new
                        {
                            Id = 129,
                            Code = "EPPL",
                            LastPrice = 0.000m,
                            Name = "الأهرام للطباعة والتغليف",
                            Sector = "ورق و مواد تعبئة و تغليف"
                        },
                        new
                        {
                            Id = 130,
                            Code = "ESRS",
                            ExtraSector = "حديد",
                            Indicator = "EGX30",
                            LastPrice = 100.800m,
                            Name = "حديد عز",
                            Sector = "موارد أساسية"
                        },
                        new
                        {
                            Id = 131,
                            Code = "ETEL",
                            Indicator = "EGX30",
                            LastPrice = 33.800m,
                            Name = "المصرية للإتصالات",
                            Sector = "اتصالات و اعلام و تكنولوجيا المعلومات"
                        },
                        new
                        {
                            Id = 132,
                            Code = "FAIT",
                            Indicator = "EGX30",
                            LastPrice = 32.490m,
                            Name = "بنك فيصل الإسلامي جنيه",
                            Sector = "البنوك"
                        },
                        new
                        {
                            Id = 133,
                            Code = "FIRE",
                            LastPrice = 0.000m,
                            Name = "الأولي للاستثمار",
                            Sector = "الشركات الصغيرة والمتوسطة"
                        },
                        new
                        {
                            Id = 134,
                            Code = "FTNS",
                            LastPrice = 0.000m,
                            Name = "فتنس برايم للأندية الصحية",
                            Sector = "الشركات الصغيرة والمتوسطة"
                        },
                        new
                        {
                            Id = 135,
                            Code = "GDWA",
                            Indicator = "EGX70",
                            LastPrice = 5.080m,
                            Name = "جدوى للتنمية الصناعية",
                            Sector = "خدمات مالية غير مصرفية"
                        },
                        new
                        {
                            Id = 136,
                            Code = "GGCC",
                            Indicator = "EGX70",
                            LastPrice = 0.388m,
                            Name = "الجيزة العامة للمقاولات",
                            Sector = "مقاولات و إنشاءات هندسية"
                        },
                        new
                        {
                            Id = 137,
                            Code = "GMCI",
                            Indicator = "",
                            LastPrice = 0.000m,
                            Name = "جي إم سي",
                            Sector = "تجارة و موزعون"
                        },
                        new
                        {
                            Id = 138,
                            Code = "GOCO",
                            LastPrice = 0.000m,
                            Name = "جولدن كوست",
                            Sector = "سياحة و ترفيه"
                        },
                        new
                        {
                            Id = 139,
                            Code = "GRCA",
                            LastPrice = 0.000m,
                            Name = "جراند انفستمنت القابضة للاستثمارات المالية",
                            Sector = "خدمات مالية غير مصرفية"
                        },
                        new
                        {
                            Id = 140,
                            Code = "GSSC",
                            LastPrice = 0.000m,
                            Name = "العامة للصوامع والتخزين",
                            Sector = "الأغذية"
                        },
                        new
                        {
                            Id = 141,
                            Code = "HDBK",
                            Indicator = "EGX70",
                            LastPrice = 43.990m,
                            Name = "بنك التعمير والإسكان",
                            Sector = "البنوك"
                        },
                        new
                        {
                            Id = 142,
                            Code = "HRHO",
                            Indicator = "EGX30",
                            LastPrice = 23.200m,
                            Name = "اي اف جي هيرميس القابضة",
                            Sector = "خدمات مالية غير مصرفية"
                        },
                        new
                        {
                            Id = 143,
                            Code = "ICID",
                            LastPrice = 0.000m,
                            Name = "العالمية للاستثمار والتنمية",
                            Sector = "عقارات"
                        },
                        new
                        {
                            Id = 144,
                            Code = "IDRIE",
                            LastPrice = 0.000m,
                            Name = "الإسماعيلية الجديدة للتطوير",
                            Sector = "عقارات"
                        },
                        new
                        {
                            Id = 145,
                            Code = "IFAP",
                            Indicator = "EGX70",
                            LastPrice = 14.730m,
                            Name = "الدولية للمحاصيل الزراعية",
                            Sector = "تجارة و موزعون"
                        },
                        new
                        {
                            Id = 146,
                            Code = "IRON",
                            ExtraSector = "حديد",
                            LastPrice = 0.000m,
                            Name = "الحديد والصلب المصرية",
                            Sector = "موارد أساسية"
                        },
                        new
                        {
                            Id = 147,
                            Code = "JUFO",
                            Indicator = "EGX30",
                            LastPrice = 29.230m,
                            Name = "جهينة",
                            Sector = "الأغذية"
                        },
                        new
                        {
                            Id = 148,
                            Code = "KABO",
                            LastPrice = 0.000m,
                            Name = "كابو",
                            Sector = "المنسوجات"
                        },
                        new
                        {
                            Id = 149,
                            Code = "KRDI",
                            Indicator = "EGX70",
                            LastPrice = 0.510m,
                            Name = "نهر الخير للتنمية",
                            Sector = "خدمات و منتجات صناعية و سيارات"
                        },
                        new
                        {
                            Id = 150,
                            Code = "LUTS",
                            LastPrice = 0.000m,
                            Name = "لوتس للاستثمارات الزراعية والتنمية",
                            Sector = "أخرى"
                        },
                        new
                        {
                            Id = 151,
                            Code = "MBEN",
                            LastPrice = 0.000m,
                            Name = "ام بي",
                            Sector = "الشركات الصغيرة والمتوسطة"
                        },
                        new
                        {
                            Id = 152,
                            Code = "MBSC",
                            ExtraSector = "أسمنت",
                            LastPrice = 0.000m,
                            Name = "مصر بني سويف للأسمنت",
                            Sector = "مواد البناء"
                        },
                        new
                        {
                            Id = 153,
                            Code = "MCRO",
                            Indicator = "EGX70",
                            LastPrice = 1.800m,
                            Name = "ماكرو جروب",
                            Sector = "الصحة"
                        },
                        new
                        {
                            Id = 154,
                            Code = "MFSC",
                            LastPrice = 0.000m,
                            Name = "مصر للأسواق الحرة",
                            Sector = "تجارة و موزعون"
                        },
                        new
                        {
                            Id = 155,
                            Code = "MHOT",
                            LastPrice = 0.000m,
                            Name = "مصر للفنادق",
                            Sector = "سياحة و ترفيه"
                        },
                        new
                        {
                            Id = 156,
                            Code = "MIPH",
                            LastPrice = 0.000m,
                            Name = "مينا فارم للأدوية",
                            Sector = "الصحة"
                        },
                        new
                        {
                            Id = 157,
                            Code = "MOED",
                            LastPrice = 0.000m,
                            Name = "المصرية لنظم التعليم الحديثة",
                            Sector = "التعليم"
                        },
                        new
                        {
                            Id = 158,
                            Code = "MOIL",
                            Indicator = "EGX70",
                            LastPrice = 0.375m,
                            Name = "الخدمات الملاحية و البترولية - ماريديف",
                            Sector = "طاقة و خدمات مساندة"
                        },
                        new
                        {
                            Id = 159,
                            Code = "MPCI",
                            LastPrice = 0.000m,
                            Name = "ممفيس للأدوية",
                            Sector = "الصحة"
                        },
                        new
                        {
                            Id = 160,
                            Code = "MPCO",
                            ExtraSector = "دواجن",
                            LastPrice = 0.000m,
                            Name = "المنصورة للدواجن",
                            Sector = "الأغذية"
                        },
                        new
                        {
                            Id = 161,
                            Code = "NEDA",
                            LastPrice = 0.000m,
                            Name = "نيوداب",
                            Sector = "الأغذية"
                        },
                        new
                        {
                            Id = 162,
                            Code = "NHPS",
                            LastPrice = 0.000m,
                            Name = "الوطنية للإسكان",
                            Sector = "عقارات"
                        },
                        new
                        {
                            Id = 163,
                            Code = "NINH",
                            LastPrice = 0.000m,
                            Name = "مستشفى النزهة",
                            Sector = "الصحة"
                        },
                        new
                        {
                            Id = 164,
                            Code = "NIPH",
                            LastPrice = 0.000m,
                            Name = "النيل للأدوية",
                            Sector = "الصحة"
                        },
                        new
                        {
                            Id = 165,
                            Code = "OBRI",
                            LastPrice = 0.000m,
                            Name = "العبور للاستثمار العقاري",
                            Sector = "عقارات"
                        },
                        new
                        {
                            Id = 166,
                            Code = "OCDI",
                            Indicator = "EGX70",
                            LastPrice = 71.050m,
                            Name = "سوديك",
                            Sector = "عقارات"
                        },
                        new
                        {
                            Id = 167,
                            Code = "OCPH",
                            LastPrice = 0.000m,
                            Name = "أكتوبر فارما",
                            Sector = "الصحة"
                        },
                        new
                        {
                            Id = 168,
                            Code = "ODIN",
                            LastPrice = 0.000m,
                            Name = "أودن للاستثمارات المالية",
                            Sector = "خدمات مالية غير مصرفية"
                        },
                        new
                        {
                            Id = 169,
                            Code = "OFH",
                            Indicator = "EGX70",
                            LastPrice = 0.310m,
                            Name = "أوراسكوم للاستثمارات المالية القابضة",
                            Sector = "خدمات مالية غير مصرفية"
                        },
                        new
                        {
                            Id = 170,
                            Code = "OIH",
                            Indicator = "EGX70",
                            LastPrice = 0.380m,
                            Name = "أوراسكوم للاستثمار",
                            Sector = "خدمات مالية غير مصرفية"
                        },
                        new
                        {
                            Id = 171,
                            Code = "ORAS",
                            LastPrice = 0.000m,
                            Name = "أوراسكوم كونستراكشون",
                            Sector = "مقاولات و إنشاءات هندسية"
                        },
                        new
                        {
                            Id = 172,
                            Code = "PACH",
                            ExtraSector = "دهانات",
                            LastPrice = 0.000m,
                            Name = "البويات والصناعات الكيماوية",
                            Sector = "موارد أساسية"
                        },
                        new
                        {
                            Id = 173,
                            Code = "PORT",
                            LastPrice = 0.000m,
                            Name = "بورتو جروب",
                            Sector = "عقارات"
                        },
                        new
                        {
                            Id = 174,
                            Code = "PSAD",
                            LastPrice = 0.000m,
                            Name = "الصعيد العامة للمقاولات",
                            Sector = "مقاولات و إنشاءات هندسية"
                        },
                        new
                        {
                            Id = 175,
                            Code = "QNBA",
                            Indicator = "EGX30",
                            LastPrice = 31.000m,
                            Name = "بنك قطر الوطني",
                            Sector = "البنوك"
                        },
                        new
                        {
                            Id = 176,
                            Code = "RACT",
                            LastPrice = 0.000m,
                            Name = "ركت للتأمين",
                            Sector = "خدمات مالية غير مصرفية"
                        },
                        new
                        {
                            Id = 177,
                            Code = "REAC",
                            LastPrice = 0.000m,
                            Name = "ريبو للاستثمار",
                            Sector = "خدمات مالية غير مصرفية"
                        },
                        new
                        {
                            Id = 178,
                            Code = "RTVC",
                            Indicator = "EGX70",
                            LastPrice = 2.500m,
                            Name = "الرائدة للاستثمار",
                            Sector = "عقارات"
                        },
                        new
                        {
                            Id = 179,
                            Code = "SAUD",
                            LastPrice = 0.000m,
                            Name = "البنك السعودي المصري",
                            Sector = "البنوك"
                        },
                        new
                        {
                            Id = 180,
                            Code = "SCEM",
                            ExtraSector = "أسمنت",
                            LastPrice = 0.000m,
                            Name = "سيناء للأسمنت",
                            Sector = "مواد البناء"
                        },
                        new
                        {
                            Id = 181,
                            Code = "SEIG",
                            LastPrice = 0.000m,
                            Name = "الشرقية الوطنية للأمن الغذائي",
                            Sector = "الأغذية"
                        },
                        new
                        {
                            Id = 182,
                            Code = "SIPM",
                            LastPrice = 0.000m,
                            Name = "سبأ الدولية للأدوية",
                            Sector = "الصحة"
                        },
                        new
                        {
                            Id = 183,
                            Code = "SKPC",
                            Indicator = "EGX30",
                            LastPrice = 35.500m,
                            Name = "سيدي كرير",
                            Sector = "بتروكيماويات"
                        },
                        new
                        {
                            Id = 184,
                            Code = "SMFR",
                            LastPrice = 0.000m,
                            Name = "سامكريت",
                            Sector = "مواد البناء"
                        },
                        new
                        {
                            Id = 185,
                            Code = "SNFC",
                            LastPrice = 0.000m,
                            Name = "القناة للملاحة",
                            Sector = "خدمات النقل والشحن"
                        },
                        new
                        {
                            Id = 186,
                            Code = "SPIN",
                            LastPrice = 0.000m,
                            Name = "الإسكندرية للغزل",
                            Sector = "النسيج"
                        },
                        new
                        {
                            Id = 187,
                            Code = "SRWA",
                            LastPrice = 0.000m,
                            Name = "الصناعات الدوائية",
                            Sector = "الصحة"
                        },
                        new
                        {
                            Id = 188,
                            Code = "STQN",
                            LastPrice = 0.000m,
                            Name = "جنوب القاهرة لتوزيع الكهرباء",
                            Sector = "طاقة و خدمات مساندة"
                        },
                        new
                        {
                            Id = 189,
                            Code = "SVCE",
                            ExtraSector = "أسمنت",
                            Indicator = "EGX70",
                            LastPrice = 2.600m,
                            Name = "جنوب الوادي للأسمنت",
                            Sector = "مواد البناء"
                        },
                        new
                        {
                            Id = 190,
                            Code = "TAMR",
                            LastPrice = 0.000m,
                            Name = "تامر",
                            Sector = "تجارة و موزعون"
                        },
                        new
                        {
                            Id = 191,
                            Code = "TORA",
                            ExtraSector = "أسمنت",
                            LastPrice = 0.000m,
                            Name = "طور سيناء",
                            Sector = "مواد البناء"
                        },
                        new
                        {
                            Id = 192,
                            Code = "TRTO",
                            LastPrice = 0.000m,
                            Name = "النقل والسياحة",
                            Sector = "سياحة و ترفيه"
                        },
                        new
                        {
                            Id = 193,
                            Code = "UCFM",
                            LastPrice = 0.000m,
                            Name = "المتحدة لصناعة الأدوية",
                            Sector = "الصحة"
                        },
                        new
                        {
                            Id = 194,
                            Code = "UEFM",
                            LastPrice = 0.000m,
                            Name = "مطاحن مصر العليا",
                            Sector = "الأغذية"
                        },
                        new
                        {
                            Id = 195,
                            Code = "UEGC",
                            ExtraSector = "سيراميك و خزف",
                            LastPrice = 0.000m,
                            Name = "العامة لمنتجات الخزف",
                            Sector = "مواد البناء"
                        },
                        new
                        {
                            Id = 196,
                            Code = "UNIT_",
                            LastPrice = 0.000m,
                            Name = "يونيفرسال",
                            Sector = "ورق و مواد تعبئة و تغليف"
                        },
                        new
                        {
                            Id = 197,
                            Code = "VAIH",
                            LastPrice = 0.000m,
                            Name = "فاليو للاستثمار",
                            Sector = "خدمات مالية غير مصرفية"
                        },
                        new
                        {
                            Id = 198,
                            Code = "WKOL",
                            LastPrice = 0.000m,
                            Name = "وادي كوم امبو",
                            Sector = "عقارات"
                        },
                        new
                        {
                            Id = 199,
                            Code = "ZEOT",
                            LastPrice = 0.000m,
                            Name = "مطاحن شرق الدلتا",
                            Sector = "الأغذية"
                        },
                        new
                        {
                            Id = 200,
                            Code = "EBDP",
                            LastPrice = 0.000m,
                            Name = "البنك المصري لتنمية الصادرات",
                            Sector = "البنوك"
                        },
                        new
                        {
                            Id = 201,
                            Code = "ELTF",
                            LastPrice = 0.000m,
                            Name = "دلتا للتأمين",
                            Sector = "خدمات مالية غير مصرفية"
                        },
                        new
                        {
                            Id = 202,
                            Code = "EMRI",
                            LastPrice = 0.000m,
                            Name = "القاهرة الوطنية للاستثمار",
                            Sector = "خدمات مالية غير مصرفية"
                        },
                        new
                        {
                            Id = 203,
                            Code = "FNAR",
                            LastPrice = 0.000m,
                            Name = "الفنار",
                            Sector = "أخرى"
                        },
                        new
                        {
                            Id = 204,
                            Code = "GOSO",
                            LastPrice = 0.000m,
                            Name = "جولدن سول",
                            Sector = "أخرى"
                        },
                        new
                        {
                            Id = 205,
                            Code = "HCFI",
                            LastPrice = 0.000m,
                            Name = "العاصمة للتمويل",
                            Sector = "خدمات مالية غير مصرفية"
                        },
                        new
                        {
                            Id = 206,
                            Code = "IDHC",
                            LastPrice = 0.000m,
                            Name = "انترناشيونال دراجون",
                            Sector = "أخرى"
                        },
                        new
                        {
                            Id = 207,
                            Code = "IDRE",
                            LastPrice = 0.000m,
                            Name = "ايجيبت انترناشيونال",
                            Sector = "عقارات"
                        },
                        new
                        {
                            Id = 208,
                            Code = "KWIN",
                            LastPrice = 0.000m,
                            Name = "كوين سيرفس",
                            Sector = "خدمات مالية غير مصرفية"
                        },
                        new
                        {
                            Id = 209,
                            Code = "MAFI",
                            LastPrice = 0.000m,
                            Name = "مصر للتنمية",
                            Sector = "خدمات مالية غير مصرفية"
                        },
                        new
                        {
                            Id = 210,
                            Code = "MAMD",
                            LastPrice = 0.000m,
                            Name = "مصر لصناعة النشا والجلوكوز",
                            Sector = "الأغذية"
                        },
                        new
                        {
                            Id = 211,
                            Code = "MILS",
                            LastPrice = 0.000m,
                            Name = "مطاحن مصر الوسطى",
                            Sector = "الأغذية"
                        },
                        new
                        {
                            Id = 212,
                            Code = "MMAT",
                            LastPrice = 0.000m,
                            Name = "المصرية لتطوير صناعة البناء",
                            Sector = "مقاولات و إنشاءات هندسية"
                        },
                        new
                        {
                            Id = 213,
                            Code = "MOIN",
                            LastPrice = 0.000m,
                            Name = "المحيطات للاستثمار",
                            Sector = "خدمات مالية غير مصرفية"
                        },
                        new
                        {
                            Id = 214,
                            Code = "MOPI",
                            LastPrice = 0.000m,
                            Name = "المصرية للمنتجات السياحية",
                            Sector = "سياحة و ترفيه"
                        },
                        new
                        {
                            Id = 215,
                            Code = "MOSC",
                            LastPrice = 0.000m,
                            Name = "مصر للزيوت",
                            Sector = "الأغذية"
                        },
                        new
                        {
                            Id = 216,
                            Code = "MRS",
                            LastPrice = 0.000m,
                            Name = "مارسيليا",
                            Sector = "عقارات"
                        },
                        new
                        {
                            Id = 217,
                            Code = "NEDA_",
                            LastPrice = 0.000m,
                            Name = "النيل للمنتجات الغذائية",
                            Sector = "الأغذية"
                        },
                        new
                        {
                            Id = 218,
                            Code = "NRPD",
                            LastPrice = 0.000m,
                            Name = "النصر للملابس والمنسوجات",
                            Sector = "المنسوجات"
                        },
                        new
                        {
                            Id = 219,
                            Code = "OBMI",
                            LastPrice = 0.000m,
                            Name = "العبور للاستثمار",
                            Sector = "خدمات مالية غير مصرفية"
                        },
                        new
                        {
                            Id = 220,
                            Code = "PIBD",
                            LastPrice = 0.000m,
                            Name = "البحر الأحمر للتنمية",
                            Sector = "عقارات"
                        },
                        new
                        {
                            Id = 221,
                            Code = "PMSI",
                            LastPrice = 0.000m,
                            Name = "الدولية للصناعات الطبية",
                            Sector = "الصحة"
                        },
                        new
                        {
                            Id = 222,
                            Code = "SAFA",
                            LastPrice = 0.000m,
                            Name = "صفا",
                            Sector = "خدمات مالية غير مصرفية"
                        },
                        new
                        {
                            Id = 223,
                            Code = "TALM",
                            LastPrice = 0.000m,
                            Name = "تعمير",
                            Sector = "عقارات"
                        },
                        new
                        {
                            Id = 224,
                            Code = "UTOP",
                            LastPrice = 0.000m,
                            Name = "يوتوبيا",
                            Sector = "عقارات"
                        });
                });

            modelBuilder.Entity("Investify.Models.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrokerageCompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProcessDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProcessType")
                        .HasColumnType("int");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<decimal>("StockPrice")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrokerageCompanyId");

                    b.HasIndex("StockId");

                    b.HasIndex("UserId");

                    b.HasIndex("WalletId");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("Investify.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BrokerageCompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrokerageCompanyId");

                    b.HasIndex("UserId");

                    b.HasIndex("WalletId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1000000m,
                            BrokerageCompanyId = 4,
                            Date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 0,
                            UserId = 1,
                            WalletId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 1500000m,
                            BrokerageCompanyId = 4,
                            Date = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Type = 0,
                            UserId = 1,
                            WalletId = 2
                        });
                });

            modelBuilder.Entity("Investify.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserHashPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserLoginName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserRealName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserRole")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "youssef.naguib@example.com",
                            UserHashPassword = "hashed_password",
                            UserLoginName = "youssef_naguib",
                            UserRealName = "Youssef Mohsen Tharwat Naguib",
                            UserRole = 0
                        });
                });

            modelBuilder.Entity("Investify.Models.Wallet", b =>
                {
                    b.Property<int>("WalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WalletId"));

                    b.Property<int>("BrokerageCompanyId")
                        .HasColumnType("int");

                    b.Property<decimal>("CommissionRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("WalletName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("WalletId");

                    b.HasIndex("BrokerageCompanyId");

                    b.HasIndex("UserId");

                    b.ToTable("Wallets");

                    b.HasData(
                        new
                        {
                            WalletId = 1,
                            BrokerageCompanyId = 4,
                            CommissionRate = 0.0005m,
                            UserId = 1,
                            WalletName = "Tycoon Main Wallet"
                        },
                        new
                        {
                            WalletId = 2,
                            BrokerageCompanyId = 4,
                            CommissionRate = 0.0005m,
                            UserId = 1,
                            WalletName = "Tycoon Savings Wallet"
                        });
                });

            modelBuilder.Entity("Investify.Models.WalletStock", b =>
                {
                    b.Property<int>("WalletStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WalletStockId"));

                    b.Property<decimal>("BuyPricePerUnit")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("CurrentPricePerUnit")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("StockId")
                        .HasColumnType("int");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("WalletStockId");

                    b.HasIndex("StockId");

                    b.HasIndex("WalletId");

                    b.ToTable("WalletStocks");
                });

            modelBuilder.Entity("Investify.Models.Trade", b =>
                {
                    b.HasOne("Investify.Models.BrokerageCompany", "BrokerageCompany")
                        .WithMany("Trades")
                        .HasForeignKey("BrokerageCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Investify.Models.Stock", "Stock")
                        .WithMany("Trades")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Investify.Models.User", "User")
                        .WithMany("Trades")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Investify.Models.Wallet", "Wallet")
                        .WithMany("Trades")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BrokerageCompany");

                    b.Navigation("Stock");

                    b.Navigation("User");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Investify.Models.Transaction", b =>
                {
                    b.HasOne("Investify.Models.BrokerageCompany", "BrokerageCompany")
                        .WithMany("Transactions")
                        .HasForeignKey("BrokerageCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Investify.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Investify.Models.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BrokerageCompany");

                    b.Navigation("User");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Investify.Models.Wallet", b =>
                {
                    b.HasOne("Investify.Models.BrokerageCompany", "BrokerageCompany")
                        .WithMany("Wallets")
                        .HasForeignKey("BrokerageCompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Investify.Models.User", "User")
                        .WithMany("Wallets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BrokerageCompany");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Investify.Models.WalletStock", b =>
                {
                    b.HasOne("Investify.Models.Stock", "Stock")
                        .WithMany("WalletStocks")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Investify.Models.Wallet", "Wallet")
                        .WithMany("WalletStocks")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Investify.Models.BrokerageCompany", b =>
                {
                    b.Navigation("Trades");

                    b.Navigation("Transactions");

                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("Investify.Models.Stock", b =>
                {
                    b.Navigation("Trades");

                    b.Navigation("WalletStocks");
                });

            modelBuilder.Entity("Investify.Models.User", b =>
                {
                    b.Navigation("Trades");

                    b.Navigation("Transactions");

                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("Investify.Models.Wallet", b =>
                {
                    b.Navigation("Trades");

                    b.Navigation("Transactions");

                    b.Navigation("WalletStocks");
                });
#pragma warning restore 612, 618
        }
    }
}
